services:
  db:
    image: postgis/postgis:15-3.4  # Обязательно postgis (с расширениями)
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-secundadb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Iseedeadpeople222!}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-secundadb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/src
    restart: unless-stopped

volumes:
  postgres_data: